SOURCE=Scorch3dEarth.cpp MainMenuButton.cpp MainMenu.cpp sound.cpp TextObject.cpp ImageObject.cpp SubMenu.cpp SubMenuTest.cpp SubMenuWeapons.cpp SubMenuHardware.cpp SubMenuLandscape.cpp SubMenuPhysics.cpp SubMenuPlayOptions.cpp SubMenuSelectTanks.cpp SubMenuSound.cpp SubMenuEconomics.cpp ControlItem.cpp ControlItemSelectionBox.cpp ControlItemCheckBox.cpp Normal.cpp Vertex.cpp TerrainMaker.cpp VBOQualifer.cpp ControlItemSliderbar.cpp ControlItemButton.cpp ReadyMenu.cpp ControlItemTextField.cpp TexCoord.cpp ShopMenu.cpp Item.cpp Weapon.cpp WeaponTest.cpp ItemTest.cpp Shader.cpp ControlItemGrid.cpp ItemBigRepair.cpp ItemSmallRepair.cpp WeaponThor.cpp WeaponBFB.cpp GlobalSettings.cpp PlayerFactory.cpp Player.cpp PlayerHuman.cpp PlayerCPU.cpp TankA.cpp TankB.cpp TankC.cpp TankD.cpp TankE.cpp TankF.cpp TankG.cpp TankH.cpp Tank.cpp GameState.cpp SkyboxFactory.cpp Water.cpp VBOShaderLibrary.cpp Vector.cpp Projectile.cpp WorldCam.cpp ChaseCam.cpp LoadingScreen.cpp Inventory.cpp Explosion.cpp SpecialEffect.cpp WeaponMFB.cpp WeaponEMP.cpp WeaponAcid.cpp WeaponAtom.cpp WeaponNuke.cpp WeaponPadlock.cpp WeaponRevive.cpp WeaponTeleport.cpp ItemAntiAcid.cpp ItemCloak.cpp ItemDoubleAction.cpp ItemExtraBattery.cpp ItemFloat.cpp ItemShield.cpp WeaponDefault.cpp ParticleGenerator.cpp Particle.cpp ParticleAcid.cpp ParticleSmoke.cpp ParticleFloat.cpp
OBJECT=Scorch3dEarth.obj MainMenuButton.obj MainMenu.obj sound.obj TextObject.obj ImageObject.obj SubMenu.obj SubMenuTest.obj SubMenuWeapons.obj SubMenuHardware.obj SubMenuLandscape.obj SubMenuPhysics.obj SubMenuPlayOptions.obj SubMenuSelectTanks.obj SubMenuSound.obj SubMenuEconomics.obj ControlItem.obj ControlItemSelectionBox.obj ControlItemCheckBox.obj Normal.obj Vertex.obj TerrainMaker.obj VBOQualifer.obj ControlItemSliderbar.obj ControlItemButton.obj ReadyMenu.obj ControlItemTextField.obj TexCoord.obj ShopMenu.obj Item.obj Weapon.obj WeaponTest.obj ItemTest.obj Shader.obj ControlItemGrid.obj ItemBigRepair.obj ItemSmallRepair.obj WeaponThor.obj WeaponBFB.obj GlobalSettings.obj PlayerFactory.obj Player.obj PlayerHuman.obj PlayerCPU.obj TankA.obj TankB.obj TankC.obj TankD.obj TankE.obj TankF.obj TankG.obj TankH.obj Tank.obj GameState.obj SkyboxFactory.obj Water.obj VBOShaderLibrary.obj Vector.obj Projectile.obj WorldCam.obj ChaseCam.obj LoadingScreen.obj Inventory.obj Explosion.obj SpecialEffect.obj WeaponMFB.obj WeaponEMP.obj WeaponAcid.obj WeaponAtom.obj WeaponNuke.obj WeaponPadlock.obj WeaponRevive.obj WeaponTeleport.obj ItemAntiAcid.obj ItemCloak.obj ItemDoubleAction.obj ItemExtraBattery.obj ItemFloat.obj ItemShield.obj WeaponDefault.obj ParticleGenerator.obj Particle.obj ParticleAcid.obj ParticleSmoke.obj ParticleFloat.obj
LIBS=user32.lib kernel32.lib gdi32.lib
#SDLmain.lib
FLAGS=/EHs
Scorch3dEarth.exe : $(SOURCE)
	cl.exe $(FLAGS) $(SOURCE) $(LIBS)
	link.exe $(OBJECT) $(LIBS)
	del *.obj
