#ifndef SOUND_H
#define SOUND_H

#include <SDL/SDL.h>
#include <SDL/SDL_mixer.h>

enum SFX {
    BIG_CLICK,
    SMALL_CLICK,
    ITEM_SELECTED,
    INVALID_CLICK,
    TRANSACTION,
    KEYTYPING,
    INVENTORY_ACCESS,
    ITEM_USE1,
    ITEM_USE2,
    ITEM_USE3,
    ITEM_USE4,
    ITEM_USE_FLOAT,
    ITEM_USE_SHIELD,
    WEAPON_LOAD,
    WEAPON_UNLOAD,
    SHIELD,
    WAVE1 = 30,
    WAVE2,
    WAVE3,
    SEAGULLS1,
    SEAGULLS2,
    SEAGULLS3,
    SEAGULLS4,
    SEAGULLS5,
    TANK_CONTROL1 = 40,
    TANK_CONTROL2,
    TANK_STUCK,
    TANK_FIRE1,
    TANK_FIRE2,
    TANK_FIRE3,
    TANK_FIRE4,
    TANK_FIRE5,
    BOMB_FLY,
    ELECTRIC_ZAP1 = 60,
    ELECTRIC_ZAP2,
    EXPLOSION1,
    EXPLOSION2,
    EXPLOSION3,
    EXPLOSION_ACID,
    EXPLOSION_THOR,
    EXPLOSION_REVIVE,
    EFFECT1 = 80,
    EFFECT_ACID,
    MANUAL
};

const int MAX_SFX_FILES = 100;

const int MAINMENU = 0;
const int READYMENU_START = 1;
const int READYMENU_LOOP = 2;
const int SHOPMENU = 3;
const int GAMESTATE_ROCK = 4;
const int GAMESTATE_SNOW = 5;
const int GAMESTATE_ICE = 6;
const int GAMESTATE_MARS = 7;
const int GAMESTATE_BEACH_START = 8;
const int GAMESTATE_BEACH_LOOP = 9;
const int GAMESTATE_DESERT = 10;
const int GAMESTATE_LAVA = 11;
const int TOTAL_MUSIC_FILES = 12;

#endif